// Code generated by "stringer -type Code -linecomment"; DO NOT EDIT.

package ierror

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ServerError-10101]
	_ = x[TooManyRequests-10102]
	_ = x[ParamBindError-10103]
	_ = x[AuthorizationError-10104]
	_ = x[CallHTTPError-10105]
	_ = x[ResubmitError-10106]
	_ = x[ResubmitMsg-10107]
	_ = x[HashIdsDecodeError-10108]
	_ = x[SignatureError-10109]
	_ = x[IllegalUserName-20101]
	_ = x[UserCreateError-20102]
	_ = x[UserUpdateError-20103]
	_ = x[UserSearchError-20104]
	_ = x[ConfigEmailError-20401]
	_ = x[ConfigSaveError-20402]
	_ = x[ConfigRedisConnectError-20403]
	_ = x[ConfigMySQLConnectError-20404]
	_ = x[ConfigMySQLInstallError-20405]
	_ = x[ConfigGoVersionError-20406]
}

const (
	_Code_name_0 = "Internal Server ErrorToo Many Requests参数信息有误签名信息有误调用第三方HTTP接口失败ResubmitError请勿重复提交ID参数有误SignatureError"
	_Code_name_1 = "非法用户名创建用户失败更新用户失败查询用户失败"
	_Code_name_2 = "修改邮箱配置失败写入配置文件失败Redis连接失败MySQL连接失败MySQL初始化数据失败GoVersion不满足要求"
)

var (
	_Code_index_0 = [...]uint8{0, 21, 38, 56, 74, 105, 118, 136, 150, 164}
	_Code_index_1 = [...]uint8{0, 15, 33, 51, 69}
	_Code_index_2 = [...]uint8{0, 24, 48, 65, 82, 108, 132}
)

func (i Code) String() string {
	switch {
	case 10101 <= i && i <= 10109:
		i -= 10101
		return _Code_name_0[_Code_index_0[i]:_Code_index_0[i+1]]
	case 20101 <= i && i <= 20104:
		i -= 20101
		return _Code_name_1[_Code_index_1[i]:_Code_index_1[i+1]]
	case 20401 <= i && i <= 20406:
		i -= 20401
		return _Code_name_2[_Code_index_2[i]:_Code_index_2[i+1]]
	default:
		return "Code(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
